### PR TITLE
Better logging

### PR DESCRIPTION
**Pull request by ylt**
Implements:
 - https://github.com/openactive/openactive-test-suite/issues/15 - "Include other test failures in log files"
 - https://github.com/openactive/openactive-test-suite/issues/13 - "Include a description of expected behaviour in tests"
 - https://github.com/openactive/openactive-test-suite/issues/18 - "Clearly reference the relevant log file"
 - Groundwork necessary for https://github.com/openactive/openactive-test-suite/issues/26 - "Output a test result certification zip file" (now generates machine readable data, however no zipping)

### CODE REVIEW

**Comment by ylt** [comment]
Almost there, main thing now is that output of specs is duplicated.

openactive-integration-tests (zsh) 2020-02-20 12-08-18

**Comment by ylt** [comment]
@nickevansuk Any suggestions on how this should look? This is the console version of the output:

image
image

**Comment by nickevansuk** [comment]
Nice! Is this the only output? Or is do the outputted reports also still include the actual requests and response JSON, which are useful for debugging with the list of tests that are running

**Comment by ylt** [comment]
The plan is to generate both, just a slightly different template file for each (so console can exclude the json, but files can include it).

**Comment by nickevansuk** [comment]
Excellent! Ye output looks great! The usefulness will obviously come down to how the individual tests are named, which works well, so e.g. "should return newly created event" will need to be self-documenting in terms of what that means or is checking for. I guess that's about them having a good balance between being concise and being descriptive.

Only minor comment would be could we change the exclamation mark emoji for failure to an "X" (as in https://github.com/openactive/openactive-test-suite/issues/15#issuecomment-588159255), to make it clearer it's a failure?

**Comment by nickevansuk** [comment]
Was there anything else you were considering here? Seems useful from the screenshots?

**Comment by ylt** [comment]
Sure, will change the emoji. Almost have the file output there, will show that as well once ready.

**Comment by nickevansuk** [comment]
Amazing @ylt !

**Comment by nickevansuk** [comment]
The only other thing that might be worth including in the console is something that indicates that requests and responses were actually sent.

I've noticed a few issues with the tests where (for whatever reason) the request for C1 doesn't actually get made (e.g. due to timeout, async issues, because the endpoint doesn't exist because the implementation is still in progress, etc)

For this would it be possible to:
a) Just return a test failure that says the Call to C1 endpoint failed
b) Or perhaps better return a separate line in the console for C1 request sent, C1 response received

These might be achieved with some additional tests that are run first within "C1"

Helps to debug situations where either (i) the endpoints just aren't working at all (e.g. URL is wrong, proxy issues, etc) or (ii) the test suite isn't actually making the requests

**Comment by ylt** [comment]
Made it generate a markdown file, an example: https://gist.github.com/ylt/82a2d12d5ab94c1119e233800a5ea378

**Comment by nickevansuk** [comment]
Love it! The great thing about the markdown is that viewing it in a text editor works too, and something like VS Code can render it easily.

Can we include the status code of responses in the output (thinking about how I might go ahead and debug the markdown file example)? Especially when there's a blank in both request and response (?) - I guess see previous comment https://github.com/openactive/openactive-test-suite/pull/33#issuecomment-589029502

Also not sure the correct validation mode is being used, or maybe the latest `data-models` and `data-model-validator` is not being used? As the validation errors don't seem correct?

**Comment by ylt** [comment]
Yeah, it is supposed to be displaying status code there. I'm currently looking into it. 

It's probably an older version of master. I'll try updating to latest master and check the versions.

```handlebars
# {{{ title }}}

{{{ description }}}

Flows:
{{#each flow}}
## {{{ @key }}}
### Request
```json
{{{ json request }}}
```
### Response
{{{ response.status }}}
```json
{{{ json response.body }}}
```
### Validations
{{#each response.validations}}
* {{{ validationIcon severity }}} {{{firstLine message}}}
{{/each}}
### Specs
{{#each response.specs}}
* {{{ specIcon status }}} {{{firstLine title}}}
{{/each}}

{{/each}}
```

**Comment by ylt** [comment]
Did try pasting in the handlebars template there, but Github didn't like markdown codeblocks inside a code block.
https://github.com/openactive/openactive-test-suite/blob/118dcd150339480f25054978752ea3fa328f046b/packages/openactive-integration-tests/test/report-templates/report.md.handlebars

**Comment by nickevansuk** [comment]
Sure. Perhaps it should be prefixed with "Response Status Code: {{{ response.status }}}" (assuming that response.status is just e.g. '200')?

**Comment by ylt** [comment]
> It would be useful to have some documentation telling me about the existence of the file output as well as the console output when after I've run the tests and to explain the different files
It does actually do this :)

openactive-integration-tests (zsh) 2020-02-21 14-05-31

**Comment by henryaddison** [comment]
Yes but that gets a bit lost in the volume of output, particularly as the README doesn't even let me know there is extra output.

**Comment by nickevansuk** [comment]
Also there's an issue where the code on this branch doesn't seem to record the response from B in the logs for some reason

**Comment by ylt** [comment]
Picked up one of the code review comments as a new PR: https://github.com/openactive/openactive-test-suite/pull/35
> In JSON files in output/meta, might it be better to use an array for the flow to communicate order? Also I don't know but might a step be repeated?

Not entirely sure if it's appropriate to finish for now, but at least good progress towards it.

**Pull request merged**
