### PR TITLE
chore: Start the broker and run the tests with project's `npm start`

### PR DESCRIPTION
**Pull request by lukehesluke**
Relies on: https://github.com/openactive/openactive-test-suite/pull/106, so this should be merged first

### CODE REVIEW

**Comment by nickevansuk** [comment]
Looks great - only comment is the naming of `run-all-tests.sh`, as it doesn't necessarily run all the tests. Perhaps `test-with-broker.sh` or something?

**Comment by nickevansuk** [comment]
Ah also CI is failing... I thought we'd agreed not to make changes to `.github/workflows/reference-implementation.yml`? Maybe I misunderstood the gif at https://github.com/openactive/openactive-test-suite/pull/106#discussion_r456585130?

**Comment by lukehesluke** [comment]
Ah, the comments didn't refresh. I was looking at the comment prior to that one when I sent the gif, @nickevansuk , so I had not seen that last comment

**Comment by nickevansuk** [comment]
Curiously the failing CI is now due to the `kill` apparently not working on error (the trap failing). `trap` is a `bash` thing, so maybe something in the CI env going on

**Comment by nickevansuk** [comment]
Ah! Strange, GitHub's usually pretty good at updating the page...

**Pull request merged**
