### PR TITLE
Fix "race condition": check if previous / current step succeeded

### PR DESCRIPTION
**Pull request by ylt**

### CODE REVIEW

**Comment by nickevansuk** [comment]
So running this branch for `npm test -- test/flows/book-only/book-only-success/book-random-test.js` on the Everyone Active facade, I get the following:

Screenshot 2020-03-05 at 16 13 50

When using `npm test -- test/flows/book-only/book-only-success/book-random-test.js --reporters default` I see the exceptions being thrown, however this does not come through to the logs or console without the default reporter enabled

**Comment by nickevansuk** [comment]
Also I notice the message at the bottom:

```
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

Is this another issue?

**Comment by ylt** [comment]
Yeah, I'm still working on this.

**Comment by nickevansuk** [comment]
Also just flagging I've noticed that although the above errors screenshot might make it look like the `/get-random-opportunity` has no available random sessions, you actually get a successful response from `localhost:3000/get-random-opportunity?type=Slot` and `localhost:3000/get-random-opportunity?type=ScheduledSession`

So looks like there's something else wrong with the test suite here...

**Comment by ylt** [comment]
Yeah what I noticed in the json files, rather interesting - this single bug has stumped me for quite a long time as it's so non-obvious! Not quite got my head around the best solution yet.

**Comment by ylt** [comment]
Looks like the random opportunity endpoint is taking 21 seconds to respond. As this is so long, Jest has stopped waiting for a response and ploughed on ahead. (Timeout in the config is set to 15 seconds).

**Comment by ylt** [comment]
Oh nice! Will try that out now

**Comment by nickevansuk** [comment]
Ye the microservice was pretty inefficient. Suggest perhaps creating an intentional delay `/get-random-opportunity` via `setTimeout` in order to fix the test suite so that it clearly reports timeouts? At the moment timeouts seem to be hidden.

**Comment by ylt** [comment]
Might be something that would be best handled in the other logger branch (it's in a lot better state for these sorts of things). Think what we could make it do is log requests that have been started, but not finished.
Unfortunately a hard one to track actual response times / response, as the response comes back after the reporter has generated the reports already!

**Comment by ylt** [comment]
@nickevansuk have a new issue, not quite sure what's up with this:
openactive-broker-microservice (zsh) 2020-03-06 09-44-44

**Comment by ylt** [comment]
Seems to be fine now, think the webservice was returning truncated responses for some reason?

**Comment by nickevansuk** [comment]
We just restarted the web service to push an update so that’s probably what caused it

Sounds good re: logging requests started not finished. Could we merge in the other branch ASAP as part of this task in that case? Hadn’t clocked it was related

**Comment by ylt** [comment]
Let's have a small look at it once this branch is in - will resolve the merge conflicts and grab some screen caps / example markdown. Main difference is that the way the data is captured and stored is different (hooks into Jest internals, and is sequence based rather than storing against keys). This had the result that the layout / formatting is a little different.

**Comment by ylt** [comment]
Current status is that, the app now has the random event - but looks like it isn't finding the event in the following get-match call - looking into this.

**Comment by nickevansuk** [comment]
That's strange as get-match is working for me for both `ScheduledSession` and `Slot`:

# ScheduledSession

## random-opportunity
### Response
Response status code: 200 OK. Responded in 783.526701ms
```json
{
    "@context": "https://openactive.io/",
    "@type": "ScheduledSession",
    "@id": "https://everyoneactivebookingfacade-test.azurewebsites.net/api/identifiers/scheduled-sessions/1191B0420000415/events/2020-03-09T20%3A00%3A00Z/1190012451"
}
```
## get-match
### Response
Response status code: 200 OK. Responded in 36.408899ms
```json
{
    "data": {
        "@context": [
            "https://openactive.io/",
            "https://openactive.io/ns-beta"
        ],
        "@type": "ScheduledSession",
        "@id": "https://everyoneactivebookingfacade-test.azurewebsites.net/api/identifiers/scheduled-sessions/1191B0420000415/events/2020-03-09T20%3A00%3A00Z/1190012451",
        "identifier": 1190012451,
        "superEvent": {
            "@context": "https://openactive.io/",
            "@type": "SessionSeries",
            "@id": "https://everyoneactivebookingfacade-test.azurewebsites.net/api/identifiers/session-series/1191B0420000415",
            "identifier": "1191B0420000415",
```


# Slot
## random-opportunity
### Response
Response status code: 200 OK. Responded in 1013.045601ms
```json
{
    "@context": "https://openactive.io/",
    "@type": "Slot",
    "@id": "https://everyoneactivebookingfacade-test.azurewebsites.net/api/identifiers/facility-uses/182BADMINTON1/facility-use-slots/182BADMINTON1_2020-03-07T17-00-00"
}
```
## get-match
### Response
Response status code: 200 OK. Responded in 39.406199ms
```json
{
    "data": {
        "@context": [
            "https://openactive.io/",
            "https://openactive.io/ns-beta"
        ],
        "@type": "Slot",
        "@id": "https://everyoneactivebookingfacade-test.azurewebsites.net/api/identifiers/facility-uses/182BADMINTON1/facility-use-slots/182BADMINTON1_2020-03-07T17-00-00",
        "identifier": "182BADMINTON1_2020-03-07T17-00-00",
        "duration": "PT1H",
        "facilityUse": {
            "@context": [
                "https://openactive.io/",
                "https://openactive.io/ns-beta"
            ],
            "@type": "FacilityUse",
            "@id": "https://everyoneactivebookingfacade-test.azurewebsites.net/api/identifiers/facility-uses/182BADMINTON1",
```

**Comment by ylt** [comment]
Guess I was relying too much on my own conditions there! Yeah it's working then. Something wrong with my own code.

**Comment by nickevansuk** [comment]
No worries, glad to have helped!

**Comment by ylt** [comment]
@nickevansuk 

Got it further, back to that authentication error unfortunately.


---

# 

A successful end to end booking.

Flows:
## random-opportunity
### Response
Response status code: 200 OK. Responded in 60.267543ms
```json
{
    "@context": "https://openactive.io/",
    "@type": "ScheduledSession",
    "@id": "https://everyoneactivebookingfacade-test.azurewebsites.net/api/identifiers/scheduled-sessions/0701B021630315/events/2020-03-09T16%3A30%3A00Z/700212792"
}
```
## get-match
### Response
Response status code: 200 OK. Responded in 11.746811ms
```json
{
    "data": {
        "@context": [
            "https://openactive.io/",
            "https://openactive.io/ns-beta"
        ],
        "@type": "ScheduledSession",
        "@id": "https://everyoneactivebookingfacade-test.azurewebsites.net/api/identifiers/scheduled-sessions/0701B021630315/events/2020-03-09T16%3A30%3A00Z/700212792",
        "identifier": 700212792,
        "superEvent": {
            "@context": [
                "https://openactive.io/",
                "https://openactive.io/ns-beta"
            ],
            "@type": "SessionSeries",
            "@id": "https://everyoneactivebookingfacade-test.azurewebsites.net/api/identifiers/session-series/0701B021630315",
            "identifier": "0701B021630315",
            "name": "Gym 11-15yrs Mon 16:30",
            "attendeeInstructions": "Gym active suitable for 11-15 years. Gym and studio based sessions to improve general fitness and promote healthy lifestyles. Supervised.",
            "category": [
                "Gym Active 11-15 Yrs"
            ],
            "duration": "PT45M",
            "location": {
                "@type": "Place",
                "identifier": "0070",
                "name": "Blandford Leisure Centre",
                "address": {
                    "@type": "PostalAddress"
                }
            },
            "offers": [
                {
                    "@type": "Offer",
                    "@id": "https://everyoneactivebookingfacade-test.azurewebsites.net/api/identifiers/session-series/0701B021630315#/offers/OX-JNR",
                    "identifier": "OX-JNR",
                    "name": "Oxygen - Junior",
                    "description": "Junior Active",
                    "ageRange": {
                        "@type": "QuantitativeValue",
                        "maxValue": 13
                    },
                    "availableChannel": [
                        "https://openactive.io/OpenBookingPrepayment"
                    ],
                    "price": 4.6,
                    "priceCurrency": "GBP",
                    "validFromBeforeStartDate": "P5D"
                },
                {
                    "@type": "Offer",
                    "@id": "https://everyoneactivebookingfacade-test.azurewebsites.net/api/identifiers/session-series/0701B021630315#/offers/OX-JNR2",
                    "identifier": "OX-JNR2",
                    "name": "Oxygen - Young Adult",
                    "description": "Junior Active",
                    "ageRange": {
                        "@type": "QuantitativeValue",
                        "maxValue": 15,
                        "minValue": 14
                    },
                    "price": 4.6,
                    "priceCurrency": "GBP",
                    "validFromBeforeStartDate": "P5D"
                }
            ],
            "organizer": {
                "@type": "Organization",
                "@id": "https://everyoneactivebookingfacade-test.azurewebsites.net/api/identifiers/seller",
                "taxMode": "https://openactive.io/TaxGross"
            },
            "superEvent": {
                "@type": "EventSeries",
                "identifier": 119,
                "name": "11-15 Years Supervised Gym Sessions",
                "description": "Suitable for children aged from 11 to 15 years, these gym and studio-based sessions help to improve general fitness and to promote healthy lifestyles.\n",
                "ageRange": {
                    "@type": "QuantitativeValue",
                    "maxValue": 15,
                    "minValue": 11
                },
                "genderRestriction": "https://openactive.io/NoRestriction",
                "level": [
                    "Beginner",
                    "Intermediate",
                    "Advanced"
                ],
                "organizer": {
                    "@type": "Organization",
                    "name": "EveryoneActive",
                    "legalName": "EveryoneActive"
                },
                "beta:formattedDescription": "<p>Suitable for children aged from 11 to 15 years, these gym and studio-based sessions help to improve general fitness and to promote healthy lifestyles.</p>"
            }
        },
        "duration": "PT45M",
        "maximumAttendeeCapacity": 16,
        "remainingAttendeeCapacity": 16,
        "startDate": "2020-03-09T16:30:00+00:00",
        "endDate": "2020-03-09T17:15:00+00:00",
        "beta:sportsActivityLocation": [
            {
                "@type": "SportsActivityLocation",
                "name": "Gym Active Sessions"
            }
        ]
    }
}
```
## C1
### Request
```json
{
    "@context": "https://openactive.io/",
    "@type": "OrderQuote",
    "brokerRole": "https://openactive.io/AgentBroker",
    "broker": {
        "@type": "Organization",
        "name": "MyFitnessApp",
        "url": "https://myfitnessapp.example.com",
        "description": "A fitness app for all the community",
        "logo": {
            "@type": "ImageObject",
            "url": "http://data.myfitnessapp.org.uk/images/logo.png"
        },
        "address": {
            "@type": "PostalAddress",
            "streetAddress": "Alan Peacock Way",
            "addressLocality": "Village East",
            "addressRegion": "Middlesbrough",
            "postalCode": "TS4 3AE",
            "addressCountry": "GB"
        }
    },
    "seller": {
        "@type": "Organization",
        "@id": "https://everyoneactivebookingfacade-test.azurewebsites.net/api/identifiers/seller"
    },
    "orderedItem": [
        {
            "@type": "OrderItem",
            "position": 0,
            "acceptedOffer": {
                "@type": "Offer",
                "@id": "https://everyoneactivebookingfacade-test.azurewebsites.net/api/identifiers/session-series/0701B021630315#/offers/OX-JNR"
            },
            "orderedItem": {
                "@type": "ScheduledSession",
                "@id": "https://everyoneactivebookingfacade-test.azurewebsites.net/api/identifiers/scheduled-sessions/0701B021630315/events/2020-03-09T16%3A30%3A00Z/700212792"
            }
        }
    ]
}
```
### Response
Response status code: 401 Unauthorized. Responded in 589.596238ms
```json
{
    "@context": "https://openactive.io/",
    "@type": "InvalidAPITokenError",
    "name": "The Broker supplied an invalid API key, either malformed or expired.",
    "statusCode": 401
}
```
### Validations
* ⚠️ Recommended property `description` is missing from `InvalidAPITokenError`.
* ⚠️ Recommended property `instance` is missing from `InvalidAPITokenError`.
### Specs
* ❌️ should return 200 on success
* ❌️ should return the type 'ScheduledSession'
* ❌️ C1 Order or OrderQuote should have one orderedItem
* ✅ passes validation checks
## C2
### Specs
* ❌️ should return 200 on success
* ❌️ Order or OrderQuote should have one orderedItem
* ❌️ passes validation checks
## B
### Specs
* ❌️ should return 200 on success
* ❌️ B Order or OrderQuote should have one orderedItem
* ❌️ Result from B should OrderItemConfirmed orderItemStatus
* ❌️ passes validation checks

**Comment by nickevansuk** [comment]
Interesting, will take a look... 

Just noting that the error output above still doesn't show why that C2 and B aren't running?

**Comment by ylt** [comment]
Those two aren't running due to C1 failing (as it's the step before in the flow). There is now more robust logic in there, to avoid unnecessarily hammering the server.

Definitely need information alongside each of the points detailing why, but that'll be logger work. The information is in the json file.

**Comment by nickevansuk** [comment]
Ok great!

**Comment by nickevansuk** [comment]
that would usually happen if the Seller ID wasn't set in the test header, however I can't seem to reproduce this...

Does the same error happen consistently?

**Comment by nickevansuk** [comment]
Ok so there are issues with the EA service still, however they are useful for the logging task you mentioned (as the failures should still be clear), and the race condition issues do seem to be resolved to an extent.

Perhaps use the reference implementation to test and merge this PR, and then use the broken EA service to work on logging?

**Comment by ylt** [comment]
Thanks @nickevansuk

Moved back to the old endpoint. There are a few failures from the old endpoint not supporting the random events, but that's to be expected, so is fine :).

Compared master and this branch against it, and I'm not seeing any regressions, so all good here.

**Pull request merged**
