### PR TITLE
Further enchance logging (sequential)

### PR DESCRIPTION
**Pull request by ylt**
From the PR https://github.com/openactive/openactive-test-suite/pull/33, one of the points raised in code review was:
> "In JSON files in output/meta, might it be better to use an array for the flow to communicate order? Also I don't know but might a step be repeated?"

I agree that it's a bad structure. And also many of the expected behaviours such as using different event types may actually require this to be changed. This PR is to attempt wrangle the data into a better format.

Progress:
- [x] Log data sequentially
- [x] Render out using log format

### CODE REVIEW

**Comment by ylt** [comment]
# OA-Test-BookCCancel-Free-Success

A successful end to end booking and customer cancellation run.

##  >> Book and Cancel

##  >> Book and Cancel >> Book and Customer Cancel Success With Payment
### create-session Request
POST https://bookingsystemreferenceimplementation.azurewebsites.net/api/openbooking/test-interface/ScheduledSession
```json
{
    "@context": "https://openactive.io/",
    "@type": "ScheduledSession",
    "superEvent": {
        "@type": "SessionSeries",
        "name": "OA-Test-BookCCancel-Free-Success",
        "offers": [
            {
                "@type": "Offer",
                "price": 0
            }
        ]
    },
    "startDate": "2020-03-15T14:49:21+00:00",
    "endDate": "2020-03-16T14:49:21+00:00",
    "maximumAttendeeCapacity": 5
}
```

---

Response status code: 200 OK. Responded in 528.07648ms
```json
{
    "@context": "https://openactive.io/",
    "@type": "ScheduledSession",
    "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/scheduled-sessions/100344/events/100345"
}
```
### get-match Request
GET http://localhost:3000/get-cached-opportunity/https%3A%2F%2Fbookingsystemreferenceimplementation.azurewebsites.net%2Fapi%2Fidentifiers%2Fscheduled-sessions%2F100344%2Fevents%2F100345

---

Response status code: 200 OK. Responded in 453.700919ms
```json
{
    "state": "updated",
    "id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/scheduled-sessions/100344/events/100345",
    "modified": 1583765364081,
    "data": {
        "@context": "https://openactive.io/",
        "@type": "ScheduledSession",
        "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/scheduled-sessions/100344/events/100345",
        "superEvent": {
            "@context": "https://openactive.io/",
            "@type": "SessionSeries",
            "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/session-series/100344",
            "name": "OA-Test-BookCCancel-Free-Success",
            "offers": [
                {
                    "@type": "Offer",
                    "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/session-series/100344#/offers/0",
                    "availableChannel": [
                        "https://openactive.io/OpenBookingPrepayment"
                    ],
                    "price": 0
                }
            ],
            "organizer": {
                "@type": "Organization",
                "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/sellers/0",
                "name": "Acme Fitness Ltd",
                "taxMode": "https://openactive.io/TaxGross"
            }
        },
        "maximumAttendeeCapacity": 5,
        "remainingAttendeeCapacity": 5,
        "startDate": "2020-03-15T14:49:21+00:00",
        "endDate": "2020-03-16T14:49:21+00:00"
    }
}
```
### delete-session Request
DELETE https://bookingsystemreferenceimplementation.azurewebsites.net/api/openbooking/test-interface/ScheduledSession/https%3A%2F%2Fbookingsystemreferenceimplementation.azurewebsites.net%2Fapi%2Fidentifiers%2Fscheduled-sessions%2F100344%2Fevents%2F100345

---

Response status code: 404 Not Found. Responded in 476.731004ms

##  >> Book and Cancel >> Book and Customer Cancel Success With Payment >> C1
### C1 Request
PUT https://bookingsystemreferenceimplementation.azurewebsites.net/api/openbooking/order-quote-templates/bb5d6088-d108-5c77-98cf-5801e0608c50
```json
{
    "@context": "https://openactive.io/",
    "@type": "OrderQuote",
    "brokerRole": "https://openactive.io/AgentBroker",
    "broker": {
        "@type": "Organization",
        "name": "MyFitnessApp",
        "url": "https://myfitnessapp.example.com",
        "description": "A fitness app for all the community",
        "logo": {
            "@type": "ImageObject",
            "url": "http://data.myfitnessapp.org.uk/images/logo.png"
        },
        "address": {
            "@type": "PostalAddress",
            "streetAddress": "Alan Peacock Way",
            "addressLocality": "Village East",
            "addressRegion": "Middlesbrough",
            "postalCode": "TS4 3AE",
            "addressCountry": "GB"
        }
    },
    "seller": {
        "@type": "Organization",
        "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/sellers/0"
    },
    "orderedItem": [
        {
            "@type": "OrderItem",
            "position": 0,
            "acceptedOffer": {
                "@type": "Offer",
                "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/session-series/100344#/offers/0"
            },
            "orderedItem": {
                "@type": "ScheduledSession",
                "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/scheduled-sessions/100344/events/100345"
            }
        }
    ]
}
```

---

Response status code: 200 OK. Responded in 476.602611ms
```json
{
    "@context": "https://openactive.io/",
    "@type": "OrderQuote",
    "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/openbooking/order-quotes/bb5d6088-d108-5c77-98cf-5801e0608c50",
    "orderRequiresApproval": false,
    "bookingService": {
        "@type": "BookingService",
        "name": "Acme booking system",
        "termsOfService": [
            {
                "@type": "PrivacyPolicy",
                "name": "Privacy Policy",
                "requiresExplicitConsent": false,
                "url": "https://example.com/privacy.html"
            }
        ],
        "url": "https://example.com"
    },
    "broker": {
        "@type": "Organization",
        "name": "MyFitnessApp",
        "url": "https://myfitnessapp.example.com"
    },
    "brokerRole": "https://openactive.io/AgentBroker",
    "orderedItem": [
        {
            "@type": "OrderItem",
            "acceptedOffer": {
                "@type": "Offer",
                "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/session-series/100344#/offers/0",
                "price": 0,
                "priceCurrency": "GBP"
            },
            "allowCustomerCancellationFullRefund": true,
            "orderedItem": {
                "@type": "ScheduledSession",
                "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/scheduled-sessions/100344/events/100345",
                "superEvent": {
                    "@type": "SessionSeries",
                    "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/session-series/100344",
                    "name": "OA-Test-BookCCancel-Free-Success",
                    "activity": [
                        {
                            "@type": "Concept",
                            "@id": "https://openactive.io/activity-list#6bdea630-ad22-4e58-98a3-bca26ee3f1da",
                            "inScheme": "https://openactive.io/activity-list",
                            "prefLabel": "Rave Fitness"
                        }
                    ],
                    "location": {
                        "@type": "Place",
                        "name": "Fake fitness studio",
                        "geo": {
                            "@type": "GeoCoordinates",
                            "latitude": 51.6201,
                            "longitude": 0.302396
                        }
                    },
                    "url": "https://example.com/events/100344"
                },
                "maximumAttendeeCapacity": 5,
                "remainingAttendeeCapacity": 5,
                "startDate": "2020-03-15T14:49:21+00:00",
                "endDate": "2020-03-16T14:49:21+00:00"
            },
            "position": 0,
            "unitTaxSpecification": [
                {
                    "@type": "TaxChargeSpecification",
                    "name": "VAT at 20%",
                    "price": 0,
                    "priceCurrency": "GBP",
                    "rate": 0.2
                }
            ]
        }
    ],
    "seller": {
        "@type": "Organization",
        "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/sellers/0",
        "name": "Acme Fitness Ltd",
        "taxMode": "https://openactive.io/TaxGross"
    },
    "totalPaymentDue": {
        "@type": "PriceSpecification",
        "price": 0,
        "priceCurrency": "GBP"
    },
    "totalPaymentTax": [
        {
            "@type": "TaxChargeSpecification",
            "name": "VAT at 20%",
            "price": 0,
            "priceCurrency": "GBP",
            "rate": 0.2
        }
    ]
}
```
### Specs
 * ✅ should return 200 on success
 * ✅ should return the type 'ScheduledSession'
 * ✅ should return have the correct event 'name' of 'OA-Test-BookCCancel-Free-Success'
 * ✅ offer should have price of 0
 * ✅ OrderQuote.totalPaymentDue equal to 0
 * ✅ C1 Order or OrderQuote should have one orderedItem
##  >> Book and Cancel >> Book and Customer Cancel Success With Payment >> C1 >> validation of C1
### Specs
 * ✅ passes validation checks
### Validations
 * ⚠️ Recommended property `name` is missing from `Offer`.
 * ⚠️ Recommended property `ageRange` is missing from `Offer`.
 * ⚠️ Recommended property `eventStatus` is missing from `ScheduledSession`.
 * 📝 Data consumers will assume that there is no gender restriction when no valid `genderRestriction` is supplied on a `ScheduledSession`.
 * 📝 Data consumers will assume that the `ageRange` is 18+ when not specified.
 * 📝 Data consumers will assume the `eventStatus` is scheduled if not specified or invalid.
 * ⚠️ Recommended property `ageRange` is missing from `SessionSeries`.
 * ⚠️ Recommended property `genderRestriction` is missing from `SessionSeries`.
 * ⚠️ Recommended property `eventStatus` is missing from `SessionSeries`.
 * 📝 Data consumers will assume that there is no gender restriction when no valid `genderRestriction` is supplied on a `SessionSeries`.
 * 📝 Data consumers will assume that the `ageRange` is 18+ when not specified.
 * 📝 Data consumers will assume the `eventStatus` is scheduled if not specified or invalid.
##  >> Book and Cancel >> Book and Customer Cancel Success With Payment >> C2
### C2 Request
PUT https://bookingsystemreferenceimplementation.azurewebsites.net/api/openbooking/order-quotes/bb5d6088-d108-5c77-98cf-5801e0608c50
```json
{
    "@context": "https://openactive.io/",
    "@type": "OrderQuote",
    "brokerRole": "https://openactive.io/AgentBroker",
    "broker": {
        "@type": "Organization",
        "name": "MyFitnessApp",
        "url": "https://myfitnessapp.example.com",
        "description": "A fitness app for all the community",
        "logo": {
            "@type": "ImageObject",
            "url": "http://data.myfitnessapp.org.uk/images/logo.png"
        },
        "address": {
            "@type": "PostalAddress",
            "streetAddress": "Alan Peacock Way",
            "addressLocality": "Village East",
            "addressRegion": "Middlesbrough",
            "postalCode": "TS4 3AE",
            "addressCountry": "GB"
        }
    },
    "seller": {
        "@type": "Organization",
        "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/sellers/0"
    },
    "customer": {
        "@type": "Person",
        "email": "geoffcapes@example.com",
        "telephone": "020 811 8055",
        "givenName": "Geoff",
        "familyName": "Capes"
    },
    "orderedItem": [
        {
            "@type": "OrderItem",
            "position": 0,
            "acceptedOffer": {
                "@type": "Offer",
                "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/session-series/100344#/offers/0"
            },
            "orderedItem": {
                "@type": "ScheduledSession",
                "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/scheduled-sessions/100344/events/100345"
            }
        }
    ]
}
```

---

Response status code: 200 OK. Responded in 467.898173ms
```json
{
    "@context": "https://openactive.io/",
    "@type": "OrderQuote",
    "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/openbooking/order-quotes/bb5d6088-d108-5c77-98cf-5801e0608c50",
    "lease": {
        "@type": "Lease",
        "leaseExpires": "2020-03-09T14:54:24+00:00"
    },
    "orderRequiresApproval": false,
    "bookingService": {
        "@type": "BookingService",
        "name": "Acme booking system",
        "termsOfService": [
            {
                "@type": "PrivacyPolicy",
                "name": "Privacy Policy",
                "requiresExplicitConsent": false,
                "url": "https://example.com/privacy.html"
            }
        ],
        "url": "https://example.com"
    },
    "broker": {
        "@type": "Organization",
        "name": "MyFitnessApp",
        "url": "https://myfitnessapp.example.com"
    },
    "brokerRole": "https://openactive.io/AgentBroker",
    "customer": {
        "@type": "Person",
        "email": "geoffcapes@example.com",
        "familyName": "Capes",
        "givenName": "Geoff",
        "telephone": "020 811 8055"
    },
    "orderedItem": [
        {
            "@type": "OrderItem",
            "acceptedOffer": {
                "@type": "Offer",
                "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/session-series/100344#/offers/0",
                "price": 0,
                "priceCurrency": "GBP"
            },
            "allowCustomerCancellationFullRefund": true,
            "orderedItem": {
                "@type": "ScheduledSession",
                "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/scheduled-sessions/100344/events/100345",
                "superEvent": {
                    "@type": "SessionSeries",
                    "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/session-series/100344",
                    "name": "OA-Test-BookCCancel-Free-Success",
                    "activity": [
                        {
                            "@type": "Concept",
                            "@id": "https://openactive.io/activity-list#6bdea630-ad22-4e58-98a3-bca26ee3f1da",
                            "inScheme": "https://openactive.io/activity-list",
                            "prefLabel": "Rave Fitness"
                        }
                    ],
                    "location": {
                        "@type": "Place",
                        "name": "Fake fitness studio",
                        "geo": {
                            "@type": "GeoCoordinates",
                            "latitude": 51.6201,
                            "longitude": 0.302396
                        }
                    },
                    "url": "https://example.com/events/100344"
                },
                "maximumAttendeeCapacity": 5,
                "remainingAttendeeCapacity": 5,
                "startDate": "2020-03-15T14:49:21+00:00",
                "endDate": "2020-03-16T14:49:21+00:00"
            },
            "position": 0,
            "unitTaxSpecification": [
                {
                    "@type": "TaxChargeSpecification",
                    "name": "VAT at 20%",
                    "price": 0,
                    "priceCurrency": "GBP",
                    "rate": 0.2
                }
            ]
        }
    ],
    "seller": {
        "@type": "Organization",
        "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/sellers/0",
        "name": "Acme Fitness Ltd",
        "taxMode": "https://openactive.io/TaxGross"
    },
    "totalPaymentDue": {
        "@type": "PriceSpecification",
        "price": 0,
        "priceCurrency": "GBP"
    },
    "totalPaymentTax": [
        {
            "@type": "TaxChargeSpecification",
            "name": "VAT at 20%",
            "price": 0,
            "priceCurrency": "GBP",
            "rate": 0.2
        }
    ]
}
```
### Specs
 * ✅ should return 200 on success
 * ✅ offer should have price of 0
 * ✅ Order or OrderQuote should have one orderedItem
##  >> Book and Cancel >> Book and Customer Cancel Success With Payment >> C2 >> validation of C2
### Specs
 * ✅ passes validation checks
### Validations
 * ⚠️ Recommended property `name` is missing from `Offer`.
 * ⚠️ Recommended property `ageRange` is missing from `Offer`.
 * ⚠️ Recommended property `eventStatus` is missing from `ScheduledSession`.
 * 📝 Data consumers will assume that there is no gender restriction when no valid `genderRestriction` is supplied on a `ScheduledSession`.
 * 📝 Data consumers will assume that the `ageRange` is 18+ when not specified.
 * 📝 Data consumers will assume the `eventStatus` is scheduled if not specified or invalid.
 * ⚠️ Recommended property `ageRange` is missing from `SessionSeries`.
 * ⚠️ Recommended property `genderRestriction` is missing from `SessionSeries`.
 * ⚠️ Recommended property `eventStatus` is missing from `SessionSeries`.
 * 📝 Data consumers will assume that there is no gender restriction when no valid `genderRestriction` is supplied on a `SessionSeries`.
 * 📝 Data consumers will assume that the `ageRange` is 18+ when not specified.
 * 📝 Data consumers will assume the `eventStatus` is scheduled if not specified or invalid.
##  >> Book and Cancel >> Book and Customer Cancel Success With Payment >> B
### B Request
PUT https://bookingsystemreferenceimplementation.azurewebsites.net/api/openbooking/orders/bb5d6088-d108-5c77-98cf-5801e0608c50
```json
{
    "@context": "https://openactive.io/",
    "@type": "Order",
    "brokerRole": "https://openactive.io/AgentBroker",
    "broker": {
        "@type": "Organization",
        "name": "MyFitnessApp",
        "url": "https://myfitnessapp.example.com",
        "description": "A fitness app for all the community",
        "logo": {
            "@type": "ImageObject",
            "url": "http://data.myfitnessapp.org.uk/images/logo.png"
        },
        "address": {
            "@type": "PostalAddress",
            "streetAddress": "Alan Peacock Way",
            "addressLocality": "Village East",
            "addressRegion": "Middlesbrough",
            "postalCode": "TS4 3AE",
            "addressCountry": "GB"
        }
    },
    "seller": {
        "@type": "Organization",
        "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/sellers/0"
    },
    "customer": {
        "@type": "Person",
        "email": "geoffcapes@example.com",
        "telephone": "020 811 8055",
        "givenName": "Geoff",
        "familyName": "Capes"
    },
    "orderedItem": [
        {
            "@type": "OrderItem",
            "position": 0,
            "acceptedOffer": {
                "@type": "Offer",
                "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/session-series/100344#/offers/0"
            },
            "orderedItem": {
                "@type": "ScheduledSession",
                "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/scheduled-sessions/100344/events/100345"
            }
        }
    ],
    "totalPaymentDue": {
        "@type": "PriceSpecification",
        "price": 0,
        "priceCurrency": "GBP"
    }
}
```

---

Response status code: 200 OK. Responded in 463.547923ms
```json
{
    "@context": "https://openactive.io/",
    "@type": "Order",
    "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/openbooking/orders/bb5d6088-d108-5c77-98cf-5801e0608c50",
    "bookingService": {
        "@type": "BookingService",
        "name": "Acme booking system",
        "termsOfService": [
            {
                "@type": "PrivacyPolicy",
                "name": "Privacy Policy",
                "requiresExplicitConsent": false,
                "url": "https://example.com/privacy.html"
            }
        ],
        "url": "https://example.com"
    },
    "broker": {
        "@type": "Organization",
        "name": "MyFitnessApp",
        "url": "https://myfitnessapp.example.com"
    },
    "brokerRole": "https://openactive.io/AgentBroker",
    "customer": {
        "@type": "Person",
        "email": "geoffcapes@example.com",
        "familyName": "Capes",
        "givenName": "Geoff",
        "telephone": "020 811 8055"
    },
    "orderedItem": [
        {
            "@type": "OrderItem",
            "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/openbooking/orders/bb5d6088-d108-5c77-98cf-5801e0608c50#/orderedItems/100349",
            "acceptedOffer": {
                "@type": "Offer",
                "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/session-series/100344#/offers/0",
                "price": 0,
                "priceCurrency": "GBP"
            },
            "allowCustomerCancellationFullRefund": true,
            "orderedItem": {
                "@type": "ScheduledSession",
                "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/scheduled-sessions/100344/events/100345",
                "superEvent": {
                    "@type": "SessionSeries",
                    "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/session-series/100344",
                    "name": "OA-Test-BookCCancel-Free-Success",
                    "activity": [
                        {
                            "@type": "Concept",
                            "@id": "https://openactive.io/activity-list#6bdea630-ad22-4e58-98a3-bca26ee3f1da",
                            "inScheme": "https://openactive.io/activity-list",
                            "prefLabel": "Rave Fitness"
                        }
                    ],
                    "location": {
                        "@type": "Place",
                        "name": "Fake fitness studio",
                        "geo": {
                            "@type": "GeoCoordinates",
                            "latitude": 51.6201,
                            "longitude": 0.302396
                        }
                    },
                    "url": "https://example.com/events/100344"
                },
                "maximumAttendeeCapacity": 5,
                "remainingAttendeeCapacity": 5,
                "startDate": "2020-03-15T14:49:21+00:00",
                "endDate": "2020-03-16T14:49:21+00:00"
            },
            "orderItemStatus": "https://openactive.io/OrderItemConfirmed",
            "position": 0,
            "unitTaxSpecification": [
                {
                    "@type": "TaxChargeSpecification",
                    "name": "VAT at 20%",
                    "price": 0,
                    "priceCurrency": "GBP",
                    "rate": 0.2
                }
            ]
        }
    ],
    "seller": {
        "@type": "Organization",
        "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/sellers/0",
        "name": "Acme Fitness Ltd",
        "taxMode": "https://openactive.io/TaxGross"
    },
    "totalPaymentDue": {
        "@type": "PriceSpecification",
        "price": 0,
        "priceCurrency": "GBP"
    },
    "totalPaymentTax": [
        {
            "@type": "TaxChargeSpecification",
            "name": "VAT at 20%",
            "price": 0,
            "priceCurrency": "GBP",
            "rate": 0.2
        }
    ]
}
```
### Specs
 * ✅ should return 200 on success
 * ✅ should have price of 0
 * ✅ OrderQuote.totalPaymentDue equal to 0
 * ✅ B Order or OrderQuote should have one orderedItem
 * ✅ Result from B should OrderItemConfirmed orderItemStatus
##  >> Book and Cancel >> Book and Customer Cancel Success With Payment >> B >> validation of B
### Specs
 * ✅ passes validation checks
### Validations
 * ⚠️ Recommended property `accessCode` is missing from `OrderItem`.
 * ⚠️ Recommended property `accessPass` is missing from `OrderItem`.
 * ⚠️ Recommended property `name` is missing from `Offer`.
 * ⚠️ Recommended property `ageRange` is missing from `Offer`.
 * ⚠️ Recommended property `eventStatus` is missing from `ScheduledSession`.
 * 📝 Data consumers will assume that there is no gender restriction when no valid `genderRestriction` is supplied on a `ScheduledSession`.
 * 📝 Data consumers will assume that the `ageRange` is 18+ when not specified.
 * 📝 Data consumers will assume the `eventStatus` is scheduled if not specified or invalid.
 * ⚠️ Recommended property `ageRange` is missing from `SessionSeries`.
 * ⚠️ Recommended property `genderRestriction` is missing from `SessionSeries`.
 * ⚠️ Recommended property `eventStatus` is missing from `SessionSeries`.
 * 📝 Data consumers will assume that there is no gender restriction when no valid `genderRestriction` is supplied on a `SessionSeries`.
 * 📝 Data consumers will assume that the `ageRange` is 18+ when not specified.
 * 📝 Data consumers will assume the `eventStatus` is scheduled if not specified or invalid.
##  >> Book and Cancel >> Book and Customer Cancel Success With Payment >> Orders Feed
### U Request
PATCH https://bookingsystemreferenceimplementation.azurewebsites.net/api/openbooking/orders/bb5d6088-d108-5c77-98cf-5801e0608c50
```json
{
    "@context": "https://openactive.io/",
    "@type": "Order",
    "orderedItem": [
        {
            "@type": "OrderItem",
            "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/openbooking/orders/bb5d6088-d108-5c77-98cf-5801e0608c50#/orderedItems/100349",
            "orderItemStatus": "https://openactive.io/CustomerCancelled"
        }
    ]
}
```

---

Response status code: 204 No Content. Responded in 467.654468ms
### get-order Request
GET http://localhost:3000/get-order/bb5d6088-d108-5c77-98cf-5801e0608c50

---

Response status code: 200 OK. Responded in 3631.843354ms
```json
{
    "state": "updated",
    "kind": "Order",
    "id": "bb5d6088-d108-5c77-98cf-5801e0608c50",
    "modified": 1583765365325,
    "data": {
        "@context": "https://openactive.io/",
        "@type": "Order",
        "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/openbooking/orders/bb5d6088-d108-5c77-98cf-5801e0608c50",
        "identifier": "bb5d6088-d108-5c77-98cf-5801e0608c50",
        "orderedItem": [
            {
                "@type": "OrderItem",
                "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/openbooking/orders/bb5d6088-d108-5c77-98cf-5801e0608c50#/orderedItems/100349",
                "acceptedOffer": {
                    "@type": "Offer",
                    "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/session-series/100344#/offers/0",
                    "price": 0,
                    "priceCurrency": "GBP"
                },
                "orderedItem": {
                    "@type": "ScheduledSession",
                    "@id": "https://bookingsystemreferenceimplementation.azurewebsites.net/api/identifiers/scheduled-sessions/100344/events/100345"
                },
                "orderItemStatus": "https://openactive.io/CustomerCancelled"
            }
        ],
        "totalPaymentDue": {
            "@type": "PriceSpecification",
            "price": 0,
            "priceCurrency": "GBP"
        }
    }
}
```
### Specs
 * ✅ Orders feed result should have one orderedItem
 * ✅ Orders feed OrderItem should correct price of 0
 * ✅ Orders feed totalPaymentDue should be correct
 * ✅ Order Cancellation return 204 on success
 * ✅ Orders feed should have CustomerCancelled as orderItemStatus
##  >> Book and Cancel >> Book and Customer Cancel Success With Payment >> Orders Feed >> validation of Orders feed
### Specs
 * ✅ passes validation checks
### Validations
 * ⚠️ Recommended property `allowCustomerCancellationFullRefund` is missing from `OrderItem`.
 * ⚠️ Recommended property `accessCode` is missing from `OrderItem`.
 * ⚠️ Recommended property `accessPass` is missing from `OrderItem`.
 * ⚠️ Recommended property `name` is missing from `Offer`.
 * ⚠️ Recommended property `ageRange` is missing from `Offer`.

**Comment by ylt** [comment]
@nickevansuk - example of how the new report rendering looks like in this PR ☝️

**Comment by nickevansuk** [comment]
The format looks good, but perhaps I've missed something here:
https://github.com/openactive/openactive-test-suite/pull/44#issuecomment-595826513

Wasn't this work also supposed to include "why that C2 and B aren't running?"

**Comment by ylt** [comment]
Layout OK but needs a few tweaks, to be continued in a new PR as specified in #46

**Pull request merged**
